name: 'KB Action'
author: Kailan Blanks
description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin porttitor vel erat vel hendrerit.'

branding:
  icon: 'cloud-lightning'
  color: 'red'

inputs:
  project_directory:
    description: 'Directory of the project to do nothing to, relative to the repository root.'
    required: false
    default: './'

runs:
  using: node12
  pre: build/index.js
  main: deploy/index.js
