name: 'Kailan\'s GitHub Action'
author: Kailan Blanks
description: 'It doesn\'t do much.'

branding:
  icon: 'cloud-lightning'
  color: 'red'

inputs:
  project_directory:
    description: 'Directory of the project to do nothing to, relative to the repository root.'
    required: false
    default: './'

runs:
  using: "composite"
  steps: 
    - run: echo Hello World.
      shell: bash
