name: 'Deploy a package'
author: 'Kailan Blanks'
description: 'Deploy'

branding:
  icon: 'layers'
  color: 'red'

runs:
  using: 'node12'
  main: 'index.js'

inputs:
  project_directory:
    description: 'Directory of the project to do nothing to, relative to the repository root.'
    required: false
    default: './'
